version: '3.8'
services:
    nginx:
        restart: always
        build:
            context: ./.nginx
            dockerfile: Dockerfile
            args:
                IMAGE_NAME_3000: app
                IMAGE_NAME_3001: app
                IMAGE_NAME_3002: app
        ports:
            - '3010:3010'
            - '3011:3011'
            - '3012:3012'
        depends_on:
            - app
        networks:
            - app-network

    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                BUILD_TYPE: 'SINGLE'
                USE_LOCALHOST: 'TRUE'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
