services:
    nginx:
        restart: always
        image: ${DOCKER_REGISTRY}/saas_xyz_nginx
        build:
            context: ./.nginx
            dockerfile: Dockerfile
            args:
                IMAGE_NAME_3000: app

        ports:
            - '8080:3010'
            - '8081:3010'
            - '8082:3010'
        depends_on:
            - app
        networks:
            - app-network

    app:
        image: ${DOCKER_REGISTRY}/saas_xyz_app
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                BUILD_TYPE: ${BUILD_TYPE}
                BASE_CLIENT: ${BASE_CLIENT}
        expose:
            - '3010'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
