version: '3.8'
services:
    nginx:
        restart: always
        build:
            context: ./.nginx
            dockerfile: Dockerfile
            args:
                IMAGE_NAME_3000: foo
                IMAGE_NAME_3001: baz
                IMAGE_NAME_3002: bar
        ports:
            - '3010:3010'
            - '3011:3011'
            - '3012:3012'
        depends_on:
            - foo
            - bar
            - baz
        networks:
            - app-network

    foo:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                BUILD_TYPE: 'INSTANCES'
                USE_LOCALHOST: 'TRUE'
                BASE_CLIENT: 'foo'
        expose:
            - '3010'
        networks:
            - app-network

    baz:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                BUILD_TYPE: 'INSTANCES'
                USE_LOCALHOST: 'TRUE'
                BASE_CLIENT: 'baz'
        expose:
            - '3011'
        networks:
            - app-network

    bar:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                BUILD_TYPE: 'INSTANCES'
                USE_LOCALHOST: 'TRUE'
                BASE_CLIENT: 'bar'
        expose:
            - '3012'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
