# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-action.json

name: Deploy action
description: deploy to ec2

inputs:
    IMAGE_NAME:
        description: string
        required: true
    SSH_KEYDIR:
        description: string
        required: true
    HOST_NAME:
        description: string
        required: true
    AWS_REGION:
        description: string
        required: true
    AWS_ACCOUNT_ID:
        description: string
        required: true
    AWS_ACCESS_KEY_ID:
        description: string
        required: true
    AWS_SECRET_ACCESS_KEY:
        description: string
        required: true

runs:
    using: 'composite'
    steps:
        - name: Install pipx
          shell: bash
          run: |
              sudo apt update
              sudo apt install pipx
              pipx ensurepath
              sudo pipx ensurepath --global

        - name: Install ansible
          shell: bash
          run: |
              pipx install --include-deps ansible botocore boto3 --force
              pipx inject ansible botocore boto3

        - name: Deploy
          shell: bash
          env:
              AWS_REGION: ${{ inputs.AWS_REGION }}
              AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
              AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
              HOST_NAME: ${{ inputs.HOST_NAME }}
              IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
              SSH_KEYDIR: ${{ inputs.SSH_KEYDIR }}
          run: make deploy-ec2
