name: Deploy Single

on: [workflow_dispatch]

jobs:
    call-deploy-workflow:
        uses: ./.github/workflows/deploy.yaml
        with:
            ENVIRONMENT: 'deploy_env'
            CONTAINER_IMAGE_NAME: 'next-saas-single'
            IMAGE_NAME: 'next-saas/single'
            HOST_NAME: 'next_saas_single'
        secrets:
            SSH_KEY: ${{ secrets.SSH_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
