name: Deploy Single

on: [workflow_dispatch]

jobs:
    deploy-single:
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEPLOYMENT_NAME: 'next_saas_single'

        name: Deploy
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create ssh key file
              uses: ./.github/action/touch_file_with_content
              with:
                  BASE_PATH: ${HOME}
                  FILE_NAME: ${DEPLOYMENT_NAME}
                  CONTENT: ${{ secrets.SSH_KEY }}

            - name: deploy
              uses: ./.github/actions/deploy
              with:
                  CONTAINER_IMAGE_NAME: 'next-saas-single'
                  IMAGE_NAME: 'next-saas/single'
                  HOST_NAME: ${{ env.DEPLOYMENT_NAME }}
                  SSH_KEYDIR: ~/.ssh
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
