name: Deploy Single

on: [workflow_dispatch]

jobs:
    deploy-single:
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEPLOYMENT_NAME: 'next_saas_single'

        name: Deploy
        runs-on: ubuntu-latest
        environment: deploy-env
        steps:
            - name: Create ssh key file
              shell: bash
              run: |
                  touch ~/.ssh/$DEPLOYMENT_NAME
                  echo "${{ secrets.SSH_KEY }}" >> ~/$DEPLOYMENT_NAME
                  chmod 400 ~/.ssh/$DEPLOYMENT_NAME
            - name: deploy
              uses: ./.github/actions/deploy.yaml
              with:
                  ENVIRONMENT: 'deploy_env'
                  CONTAINER_IMAGE_NAME: 'next-saas-single'
                  IMAGE_NAME: 'next-saas/single'
                  HOST_NAME: ${{ env.DEPLOYMENT_NAME }}
                  SSH_KEYDIR: ~/.ssh
                  SSH_KEY: ${{ secrets.SSH_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
