# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Reusable Deploy

on:
    workflow_call:
        inputs:
            ENVIRONMENT:
                type: string
                required: true
            IMAGE_NAME:
                type: string
                required: true
            CONTAINER_IMAGE_NAME:
                type: string
                required: true
            HOST_NAME:
                type: string
                required: true
        secrets:
            SSH_KEY:
                required: true
            AWS_REGION:
                required: true
            AWS_ACCOUNT_ID:
                required: true
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true

jobs:
    deploy:
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        name: Deploy
        runs-on: ubuntu-latest
        environment: ${{ inputs.ENVIRONMENT }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install pipx
              run: |
                  sudo apt update
                  sudo apt install pipx
                  pipx ensurepath
                  sudo pipx ensurepath --global

            - name: Install ansible
              run: pipx install --include-deps ansible

            - name: Install aws
              run: pipx install awscli

            - name: Create ssh key file
              run: |
                  touch ~/.ansible_key
                  echo "${{ secrets.SSH_KEY }}" >> ~/.ansible_key
                  chmod 400 ~/.ansible_key

            - name: Get instance public ip
              id: get-instance-ip
              env:
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  INSTANCE_ID: ${{ inputs.EC2_INSTANCE_ID }}
              run: |
                  PUBLIC_IP=$(make get-ec2-instance-public-ip)
                  echo "HOST_IP=$PUBLIC_IP" >> "$GITHUB_OUTPUT"

            - name: Deploy
              env:
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  HOST_NAME: ${{ inputs.HOST_NAME }}
                  CONTAINER_IMAGE_NAME: ${{ inputs.CONTAINER_IMAGE_NAME }}
                  IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
              run: make deploy-ec2
