local:
    hosts:
        localubuntu:
            ansible_host: 192.168.0.13
            ansible_user: zaza
            ansible_password: "{{ lookup('env', 'UBUNTU_PASS') }}"
            ansible_become_pass: "{{ lookup('env', 'UBUNTU_PASS') }}"
prod:
    hosts:
        ec2-us-east-1-101:
            ansible_host: 3.218.153.101
            ansible_user: ubuntu
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
